using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// Options : https://github.com/curl/curl/blob/68f96fc9bfce90c264d4d95b91135f3ef945eea8/include/curl/curl.h#L1097
// Infos : https://github.com/curl/curl/blob/68f96fc9bfce90c264d4d95b91135f3ef945eea8/include/curl/curl.h#L2850
// Errors Codes : https://curl.se/libcurl/c/libcurl-errors.html

namespace Curly.LibCURL
{
    internal class CurlEnums
    {
        public enum HttpMethod
        {
            GET,
            HEAD,
            POST,
            PUT,
            DELETE,
            CONNECT,
            OPTIONS,
            TRACE,
            PATCH,
            PURGE
        }

        public enum HttpVersion
        {
            [Description("libcurl uses whatever it thinks fit. We do not care about what version the library uses.")]
            CURL_HTTP_VERSION_NONE,

            [Description("Enforce HTTP 1.0 requests.")]
            CURL_HTTP_VERSION_1_0,

            [Description("Enforce HTTP 1.1 requests.")]
            CURL_HTTP_VERSION_1_1,

            [Description("Attempt HTTP 2 requests. libcurl falls back to HTTP 1.1 if HTTP 2 cannot be negotiated with the server. (Added in 7.33.0)")]
            CURL_HTTP_VERSION_2_0,

            [Description("Attempt HTTP 2 over TLS (HTTPS) only. libcurl falls back to HTTP 1.1 if HTTP 2 cannot be negotiated with the HTTPS server. For clear text HTTP servers, libcurl uses 1.1. (Added in 7.47.0)")]
            CURL_HTTP_VERSION_2TLS,

            [Description("Issue non-TLS HTTP requests using HTTP/2 without HTTP/1.1 Upgrade. It requires prior knowledge that the server supports HTTP/2 straight away. HTTPS requests still do HTTP/2 the standard way with negotiated protocol version in the TLS handshake. (Added in 7.49.0)")]
            CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE,

            [Description("(Added in 7.66.0) This option makes libcurl attempt to use HTTP/3 to the host given in the URL, with fallback to earlier HTTP versions if needed.")]
            CURL_HTTP_VERSION_3,

            [Description("(Added in 7.88.0) Setting this makes libcurl attempt to use HTTP/3 directly to server given in the URL and does not downgrade to earlier HTTP version if the server does not support HTTP/3.")]
            CURL_HTTP_VERSION_3ONLY
        }

        public enum SecurityProtocol
        {
            [Description("The default acceptable version range. The minimum acceptable version is TLS v1.0 by default since version 7.39.0, unless the TLS library has stricter rules.")]
            CURL_SSLVERSION_DEFAULT,

            [Description("TLS v1.0 or later.")]
            CURL_SSLVERSION_TLSv1,

            [Description("SSL v2 - refused.")]
            CURL_SSLVERSION_SSLv2,

            [Description("SSL v3 - refused.")]
            CURL_SSLVERSION_SSLv3,

            [Description("TLS v1.0 or later (Added in version 7.34.0).")]
            CURL_SSLVERSION_TLSv1_0,

            [Description("TLS v1.1 or later (Added in version 7.34.0).")]
            CURL_SSLVERSION_TLSv1_1,

            [Description("TLS v1.2 or later (Added in version 7.34.0).")]
            CURL_SSLVERSION_TLSv1_2,

            [Description("TLS v1.3 or later (Added in version 7.52.0).")]
            CURL_SSLVERSION_TLSv1_3,

            [Description("Defines the maximum supported TLS version by libcurl, or the default value from the SSL library is used. libcurl uses a sensible default maximum, which was TLS v1.2 up to before version 7.61.0 and is TLS v1.3 since then, assuming the TLS library supports it (Added in version 7.54.0).")]
            CURL_SSLVERSION_MAX_DEFAULT,

            [Description("Defines the maximum supported TLS version as TLS v1.0 (Added in version 7.54.0).")]
            CURL_SSLVERSION_MAX_TLSv1_0,

            [Description("Defines the maximum supported TLS version as TLS v1.1 (Added in version 7.54.0).")]
            CURL_SSLVERSION_MAX_TLSv1_1,

            [Description("Defines the maximum supported TLS version as TLS v1.2 (Added in version 7.54.0).")]
            CURL_SSLVERSION_MAX_TLSv1_2,

            [Description("Defines the maximum supported TLS version as TLS v1.3 (Added in version 7.54.0).")]
            CURL_SSLVERSION_MAX_TLSv1_3
        }

        public enum Options
        {
            CURLOPT_WRITEDATA = 10001,
            CURLOPT_URL = 10002,
            CURLOPT_PORT = 3,
            CURLOPT_PROXY = 10004,
            CURLOPT_USERPWD = 10005,
            CURLOPT_PROXYUSERPWD = 10006,
            CURLOPT_RANGE = 10007,
            CURLOPT_READDATA = 10009,
            CURLOPT_ERRORBUFFER = 10010,
            CURLOPT_WRITEFUNCTION = 20011,
            CURLOPT_READFUNCTION = 20012,
            CURLOPT_TIMEOUT = 13,
            CURLOPT_INFILESIZE = 14,
            CURLOPT_POSTFIELDS = 10015,
            CURLOPT_REFERER = 10016,
            CURLOPT_FTPPORT = 10017,
            CURLOPT_USERAGENT = 10018,
            CURLOPT_LOW_SPEED_LIMIT = 19,
            CURLOPT_LOW_SPEED_TIME = 20,
            CURLOPT_RESUME_FROM = 21,
            CURLOPT_COOKIE = 10022,
            CURLOPT_HTTPHEADER = 10023,
            CURLOPT_SSLCERT = 10025,
            CURLOPT_KEYPASSWD = 10026,
            CURLOPT_CRLF = 27,
            CURLOPT_QUOTE = 10028,
            CURLOPT_HEADERDATA = 10029,
            CURLOPT_COOKIEFILE = 10031,
            CURLOPT_SSLVERSION = 32,
            CURLOPT_TIMECONDITION = 33,
            CURLOPT_TIMEVALUE = 34,
            CURLOPT_CUSTOMREQUEST = 10036,
            CURLOPT_STDERR = 10037,
            CURLOPT_POSTQUOTE = 10039,
            CURLOPT_OBSOLETE40 = 10040,
            CURLOPT_VERBOSE = 41,
            CURLOPT_HEADER = 42,
            CURLOPT_NOPROGRESS = 43,
            CURLOPT_NOBODY = 44,
            CURLOPT_FAILONERROR = 45,
            CURLOPT_UPLOAD = 46,
            CURLOPT_POST = 47,
            CURLOPT_DIRLISTONLY = 48,
            CURLOPT_APPEND = 50,
            CURLOPT_NETRC = 51,
            CURLOPT_FOLLOWLOCATION = 52,
            CURLOPT_TRANSFERTEXT = 53,
            CURLOPT_XFERINFODATA = 10057,
            CURLOPT_AUTOREFERER = 58,
            CURLOPT_PROXYPORT = 59,
            CURLOPT_POSTFIELDSIZE = 60,
            CURLOPT_HTTPPROXYTUNNEL = 61,
            CURLOPT_INTERFACE = 10062,
            CURLOPT_KRBLEVEL = 10063,
            CURLOPT_SSL_VERIFYPEER = 64,
            CURLOPT_CAINFO = 10065,
            CURLOPT_MAXREDIRS = 68,
            CURLOPT_FILETIME = 69,
            CURLOPT_TELNETOPTIONS = 10070,
            CURLOPT_MAXCONNECTS = 71,
            CURLOPT_OBSOLETE72 = 72,
            CURLOPT_FRESH_CONNECT = 74,
            CURLOPT_FORBID_REUSE = 75,
            CURLOPT_CONNECTTIMEOUT = 78,
            CURLOPT_HEADERFUNCTION = 20079,
            CURLOPT_HTTPGET = 80,
            CURLOPT_SSL_VERIFYHOST = 81,
            CURLOPT_COOKIEJAR = 10082,
            CURLOPT_SSL_CIPHER_LIST = 10083,
            CURLOPT_HTTP_VERSION = 84,
            CURLOPT_FTP_USE_EPSV = 85,
            CURLOPT_SSLCERTTYPE = 10086,
            CURLOPT_SSLKEY = 10087,
            CURLOPT_SSLKEYTYPE = 10088,
            CURLOPT_SSLENGINE = 10089,
            CURLOPT_SSLENGINE_DEFAULT = 90,
            CURLOPT_DNS_CACHE_TIMEOUT = 92,
            CURLOPT_PREQUOTE = 10093,
            CURLOPT_DEBUGFUNCTION = 20094,
            CURLOPT_DEBUGDATA = 10095,
            CURLOPT_COOKIESESSION = 96,
            CURLOPT_CAPATH = 10097,
            CURLOPT_BUFFERSIZE = 98,
            CURLOPT_NOSIGNAL = 99,
            CURLOPT_SHARE = 10100,
            CURLOPT_PROXYTYPE = 101,
            CURLOPT_ACCEPT_ENCODING = 10102,
            CURLOPT_PRIVATE = 10103,
            CURLOPT_HTTP200ALIASES = 10104,
            CURLOPT_UNRESTRICTED_AUTH = 105,
            CURLOPT_FTP_USE_EPRT = 106,
            CURLOPT_HTTPAUTH = 107,
            CURLOPT_SSL_CTX_FUNCTION = 20108,
            CURLOPT_SSL_CTX_DATA = 10109,
            CURLOPT_FTP_CREATE_MISSING_DIRS = 110,
            CURLOPT_PROXYAUTH = 111,
            CURLOPT_SERVER_RESPONSE_TIMEOUT = 112,
            CURLOPT_IPRESOLVE = 113,
            CURLOPT_MAXFILESIZE = 114,
            CURLOPT_INFILESIZE_LARGE = 30115,
            CURLOPT_RESUME_FROM_LARGE = 30116,
            CURLOPT_MAXFILESIZE_LARGE = 30117,
            CURLOPT_NETRC_FILE = 10118,
            CURLOPT_USE_SSL = 119,
            CURLOPT_POSTFIELDSIZE_LARGE = 30120,
            CURLOPT_TCP_NODELAY = 121,
            CURLOPT_FTPSSLAUTH = 129,
            CURLOPT_FTP_ACCOUNT = 10134,
            CURLOPT_COOKIELIST = 10135,
            CURLOPT_IGNORE_CONTENT_LENGTH = 136,
            CURLOPT_FTP_SKIP_PASV_IP = 137,
            CURLOPT_FTP_FILEMETHOD = 138,
            CURLOPT_LOCALPORT = 139,
            CURLOPT_LOCALPORTRANGE = 140,
            CURLOPT_CONNECT_ONLY = 141,
            CURLOPT_MAX_SEND_SPEED_LARGE = 30145,
            CURLOPT_MAX_RECV_SPEED_LARGE = 30146,
            CURLOPT_FTP_ALTERNATIVE_TO_USER = 10147,
            CURLOPT_SOCKOPTFUNCTION = 20148,
            CURLOPT_SOCKOPTDATA = 10149,
            CURLOPT_SSL_SESSIONID_CACHE = 150,
            CURLOPT_SSH_AUTH_TYPES = 151,
            CURLOPT_SSH_PUBLIC_KEYFILE = 10152,
            CURLOPT_SSH_PRIVATE_KEYFILE = 10153,
            CURLOPT_FTP_SSL_CCC = 154,
            CURLOPT_TIMEOUT_MS = 155,
            CURLOPT_CONNECTTIMEOUT_MS = 156,
            CURLOPT_HTTP_TRANSFER_DECODING = 157,
            CURLOPT_HTTP_CONTENT_DECODING = 158,
            CURLOPT_NEW_FILE_PERMS = 159,
            CURLOPT_NEW_DIRECTORY_PERMS = 160,
            CURLOPT_POSTREDIR = 161,
            CURLOPT_SSH_HOST_PUBLIC_KEY_MD5 = 10162,
            CURLOPT_OPENSOCKETFUNCTION = 20163,
            CURLOPT_OPENSOCKETDATA = 10164,
            CURLOPT_COPYPOSTFIELDS = 10165,
            CURLOPT_PROXY_TRANSFER_MODE = 166,
            CURLOPT_SEEKFUNCTION = 20167,
            CURLOPT_SEEKDATA = 10168,
            CURLOPT_CRLFILE = 10169,
            CURLOPT_ISSUERCERT = 10170,
            CURLOPT_ADDRESS_SCOPE = 171,
            CURLOPT_CERTINFO = 172,
            CURLOPT_USERNAME = 10173,
            CURLOPT_PASSWORD = 10174,
            CURLOPT_PROXYUSERNAME = 10175,
            CURLOPT_PROXYPASSWORD = 10176,
            CURLOPT_NOPROXY = 10177,
            CURLOPT_TFTP_BLKSIZE = 178,
            CURLOPT_SOCKS5_GSSAPI_NEC = 180,
            CURLOPT_SSH_KNOWNHOSTS = 10183,
            CURLOPT_SSH_KEYFUNCTION = 20184,
            CURLOPT_SSH_KEYDATA = 10185,
            CURLOPT_MAIL_FROM = 10186,
            CURLOPT_MAIL_RCPT = 10187,
            CURLOPT_FTP_USE_PRET = 188,
            CURLOPT_RTSP_REQUEST = 189,
            CURLOPT_RTSP_SESSION_ID = 10190,
            CURLOPT_RTSP_STREAM_URI = 10191,
            CURLOPT_RTSP_TRANSPORT = 10192,
            CURLOPT_RTSP_CLIENT_CSEQ = 193,
            CURLOPT_RTSP_SERVER_CSEQ = 194,
            CURLOPT_INTERLEAVEDATA = 10195,
            CURLOPT_INTERLEAVEFUNCTION = 20196,
            CURLOPT_WILDCARDMATCH = 197,
            CURLOPT_CHUNK_BGN_FUNCTION = 20198,
            CURLOPT_CHUNK_END_FUNCTION = 20199,
            CURLOPT_FNMATCH_FUNCTION = 20200,
            CURLOPT_CHUNK_DATA = 10201,
            CURLOPT_FNMATCH_DATA = 10202,
            CURLOPT_RESOLVE = 10203,
            CURLOPT_TLSAUTH_USERNAME = 10204,
            CURLOPT_TLSAUTH_PASSWORD = 10205,
            CURLOPT_TLSAUTH_TYPE = 10206,
            CURLOPT_TRANSFER_ENCODING = 207,
            CURLOPT_CLOSESOCKETFUNCTION = 20208,
            CURLOPT_CLOSESOCKETDATA = 10209,
            CURLOPT_GSSAPI_DELEGATION = 210,
            CURLOPT_DNS_SERVERS = 10211,
            CURLOPT_ACCEPTTIMEOUT_MS = 212,
            CURLOPT_TCP_KEEPALIVE = 213,
            CURLOPT_TCP_KEEPIDLE = 214,
            CURLOPT_TCP_KEEPINTVL = 215,
            CURLOPT_SSL_OPTIONS = 216,
            CURLOPT_MAIL_AUTH = 10217,
            CURLOPT_SASL_IR = 218,
            CURLOPT_XFERINFOFUNCTION = 20219,
            CURLOPT_XOAUTH2_BEARER = 10220,
            CURLOPT_DNS_INTERFACE = 10221,
            CURLOPT_DNS_LOCAL_IP4 = 10222,
            CURLOPT_DNS_LOCAL_IP6 = 10223,
            CURLOPT_LOGIN_OPTIONS = 10224,
            CURLOPT_SSL_ENABLE_ALPN = 226,
            CURLOPT_EXPECT_100_TIMEOUT_MS = 227,
            CURLOPT_PROXYHEADER = 10228,
            CURLOPT_HEADEROPT = 229,
            CURLOPT_PINNEDPUBLICKEY = 10230,
            CURLOPT_UNIX_SOCKET_PATH = 10231,
            CURLOPT_SSL_VERIFYSTATUS = 232,
            CURLOPT_SSL_FALSESTART = 233,
            CURLOPT_PATH_AS_IS = 234,
            CURLOPT_PROXY_SERVICE_NAME = 10235,
            CURLOPT_SERVICE_NAME = 10236,
            CURLOPT_PIPEWAIT = 237,
            CURLOPT_DEFAULT_PROTOCOL = 10238,
            CURLOPT_STREAM_WEIGHT = 239,
            CURLOPT_STREAM_DEPENDS = 10240,
            CURLOPT_STREAM_DEPENDS_E = 10241,
            CURLOPT_TFTP_NO_OPTIONS = 242,
            CURLOPT_CONNECT_TO = 10243,
            CURLOPT_TCP_FASTOPEN = 244,
            CURLOPT_KEEP_SENDING_ON_ERROR = 245,
            CURLOPT_PROXY_CAINFO = 10246,
            CURLOPT_PROXY_CAPATH = 10247,
            CURLOPT_PROXY_SSL_VERIFYPEER = 248,
            CURLOPT_PROXY_SSL_VERIFYHOST = 249,
            CURLOPT_PROXY_SSLVERSION = 250,
            CURLOPT_PROXY_TLSAUTH_USERNAME = 10251,
            CURLOPT_PROXY_TLSAUTH_PASSWORD = 10252,
            CURLOPT_PROXY_TLSAUTH_TYPE = 10253,
            CURLOPT_PROXY_SSLCERT = 10254,
            CURLOPT_PROXY_SSLCERTTYPE = 10255,
            CURLOPT_PROXY_SSLKEY = 10256,
            CURLOPT_PROXY_SSLKEYTYPE = 10257,
            CURLOPT_PROXY_KEYPASSWD = 10258,
            CURLOPT_PROXY_SSL_CIPHER_LIST = 10259,
            CURLOPT_PROXY_CRLFILE = 10260,
            CURLOPT_PROXY_SSL_OPTIONS = 261,
            CURLOPT_PRE_PROXY = 10262,
            CURLOPT_PROXY_PINNEDPUBLICKEY = 10263,
            CURLOPT_ABSTRACT_UNIX_SOCKET = 10264,
            CURLOPT_SUPPRESS_CONNECT_HEADERS = 265,
            CURLOPT_REQUEST_TARGET = 10266,
            CURLOPT_SOCKS5_AUTH = 267,
            CURLOPT_SSH_COMPRESSION = 268,
            CURLOPT_MIMEPOST = 10269,
            CURLOPT_TIMEVALUE_LARGE = 30270,
            CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS = 271,
            CURLOPT_RESOLVER_START_FUNCTION = 20272,
            CURLOPT_RESOLVER_START_DATA = 10273,
            CURLOPT_HAPROXYPROTOCOL = 274,
            CURLOPT_DNS_SHUFFLE_ADDRESSES = 275,
            CURLOPT_TLS13_CIPHERS = 10276,
            CURLOPT_PROXY_TLS13_CIPHERS = 10277,
            CURLOPT_DISALLOW_USERNAME_IN_URL = 278,
            CURLOPT_DOH_URL = 10279,
            CURLOPT_UPLOAD_BUFFERSIZE = 280,
            CURLOPT_UPKEEP_INTERVAL_MS = 281,
            CURLOPT_CURLU = 10282,
            CURLOPT_TRAILERFUNCTION = 20283,
            CURLOPT_TRAILERDATA = 10284,
            CURLOPT_HTTP09_ALLOWED = 285,
            CURLOPT_ALTSVC_CTRL = 286,
            CURLOPT_ALTSVC = 10287,
            CURLOPT_MAXAGE_CONN = 288,
            CURLOPT_SASL_AUTHZID = 10289,
            CURLOPT_MAIL_RCPT_ALLOWFAILS = 290,
            CURLOPT_SSLCERT_BLOB = 40291,
            CURLOPT_SSLKEY_BLOB = 40292,
            CURLOPT_PROXY_SSLCERT_BLOB = 40293,
            CURLOPT_PROXY_SSLKEY_BLOB = 40294,
            CURLOPT_ISSUERCERT_BLOB = 40295,
            CURLOPT_PROXY_ISSUERCERT = 10296,
            CURLOPT_PROXY_ISSUERCERT_BLOB = 40297,
            CURLOPT_SSL_EC_CURVES = 10298,
            CURLOPT_HSTS_CTRL = 299,
            CURLOPT_HSTS = 10300,
            CURLOPT_HSTSREADFUNCTION = 20301,
            CURLOPT_HSTSREADDATA = 10302,
            CURLOPT_HSTSWRITEFUNCTION = 20303,
            CURLOPT_HSTSWRITEDATA = 10304,
            CURLOPT_AWS_SIGV4 = 10305,
            CURLOPT_DOH_SSL_VERIFYPEER = 306,
            CURLOPT_DOH_SSL_VERIFYHOST = 307,
            CURLOPT_DOH_SSL_VERIFYSTATUS = 308,
            CURLOPT_CAINFO_BLOB = 40309,
            CURLOPT_PROXY_CAINFO_BLOB = 40310,
            CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256 = 10311,
            CURLOPT_PREREQFUNCTION = 20312,
            CURLOPT_PREREQDATA = 10313,
            CURLOPT_MAXLIFETIME_CONN = 314,
            CURLOPT_MIME_OPTIONS = 315,
            CURLOPT_SSH_HOSTKEYFUNCTION = 20316,
            CURLOPT_SSH_HOSTKEYDATA = 10317,
            CURLOPT_PROTOCOLS_STR = 10318,
            CURLOPT_REDIR_PROTOCOLS_STR = 10319,
            CURLOPT_WS_OPTIONS = 320,
            CURLOPT_CA_CACHE_TIMEOUT = 321,
            CURLOPT_QUICK_EXIT = 322,
            CURLOPT_HAPROXY_CLIENT_IP = 10323,
            CURLOPT_SERVER_RESPONSE_TIMEOUT_MS = 324,
        }

        public enum Infos : int
        {
            CURLINFO_EFFECTIVE_URL = 0x100000 + 1,
            CURLINFO_RESPONSE_CODE = 0x200000 + 2,
            CURLINFO_TOTAL_TIME = 0x300000 + 3,
            CURLINFO_NAMELOOKUP_TIME = 0x300000 + 4,
            CURLINFO_CONNECT_TIME = 0x300000 + 5,
            CURLINFO_PRETRANSFER_TIME = 0x300000 + 6,
            CURLINFO_SIZE_UPLOAD_T = 0x600000 + 7,
            CURLINFO_SIZE_DOWNLOAD_T = 0x600000 + 8,
            CURLINFO_SPEED_DOWNLOAD_T = 0x600000 + 9,
            CURLINFO_HEADER_SIZE = 0x200000 + 11,
            CURLINFO_REQUEST_SIZE = 0x200000 + 12,
            CURLINFO_SSL_VERIFYRESULT = 0x200000 + 13,
            CURLINFO_FILETIME = 0x200000 + 14,
            CURLINFO_FILETIME_T = 0x600000 + 14,
            CURLINFO_CONTENT_LENGTH_DOWNLOAD_T = 0x600000 + 15,
            CURLINFO_CONTENT_LENGTH_UPLOAD_T = 0x600000 + 16,
            CURLINFO_STARTTRANSFER_TIME = 0x300000 + 17,
            CURLINFO_CONTENT_TYPE = 0x100000 + 18,
            CURLINFO_REDIRECT_TIME = 0x300000 + 19,
            CURLINFO_REDIRECT_COUNT = 0x200000 + 20,
            CURLINFO_PRIVATE = 0x100000 + 21,
            CURLINFO_HTTP_CONNECTCODE = 0x200000 + 22,
            CURLINFO_HTTPAUTH_AVAIL = 0x200000 + 23,
            CURLINFO_PROXYAUTH_AVAIL = 0x200000 + 24,
            CURLINFO_OS_ERRNO = 0x200000 + 25,
            CURLINFO_NUM_CONNECTS = 0x200000 + 26,
            CURLINFO_SSL_ENGINES = 0x400000 + 27,
            CURLINFO_REDIRECT_URL = 0x100000 + 31,
            CURLINFO_PRIMARY_IP = 0x100000 + 32,
            CURLINFO_APPCONNECT_TIME = 0x300000 + 33,
            CURLINFO_CERTINFO = 0x400000 + 34,
            CURLINFO_CONDITION_UNMET = 0x200000 + 35,
            CURLINFO_RTSP_SESSION_ID = 0x100000 + 36,
            CURLINFO_RTSP_CLIENT_CSEQ = 0x200000 + 37,
            CURLINFO_RTSP_SERVER_CSEQ = 0x200000 + 38,
            CURLINFO_RTSP_CSEQ_RECV = 0x200000 + 39,
            CURLINFO_PRIMARY_PORT = 0x200000 + 40,
            CURLINFO_LOCAL_IP = 0x100000 + 41,
            CURLINFO_TLS_SSL_PTR = 0x400000 + 45,
            CURLINFO_HTTP_VERSION = 0x200000 + 46,
            CURLINFO_TOTAL_TIME_T = 0x600000 + 50,
            CURLINFO_NAMELOOKUP_TIME_T = 0x600000 + 51,
            CURLINFO_CONNECT_TIME_T = 0x600000 + 52,
            CURLINFO_PRETRANSFER_TIME_T = 0x600000 + 53,
            CURLINFO_STARTTRANSFER_TIME_T = 0x600000 + 54,
            CURLINFO_REDIRECT_TIME_T = 0x600000 + 55,
            CURLINFO_APPCONNECT_TIME_T = 0x600000 + 56,
            CURLINFO_RETRY_AFTER = 0x600000 + 57,
            CURLINFO_EFFECTIVE_METHOD = 0x100000 + 58,
            CURLINFO_PROXY_ERROR = 0x200000 + 59,
            CURLINFO_REFERER = 0x100000 + 60,
            CURLINFO_CAINFO = 0x100000 + 61,
            CURLINFO_CAPATH = 0x100000 + 62,
            CURLINFO_XFER_ID = 0x600000 + 63,
            CURLINFO_CONN_ID = 0x600000 + 64,
            CURLINFO_QUEUE_TIME_T = 0x600000 + 65,
        }

        public static readonly Dictionary<int, string> ErrorMessages = new Dictionary<int, string>
        {
            {0, "All fine."},
            {1, "The URL you passed to libcurl used a protocol that this libcurl does not support."},
            {2, "Early initialization code failed."},
            {3, "The URL was not properly formatted."},
            {4, "A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."},
            {5, "Could not resolve proxy."},
            {6, "Could not resolve host."},
            {7, "Failed to connect() to host or proxy."},
            {8, "The server sent data libcurl could not parse."},
            {9, "We were denied access to the resource given in the URL."},
            {10, "While waiting for the server to connect back when an active FTP session is used, an error code was sent over the control connection or similar."},
            {11, "After having sent the FTP password to the server, libcurl expects a proper reply."},
            {12, "During an active FTP session while waiting for the server to connect, the CURLOPT_ACCEPTTIMEOUT_MS (or the internal default) timeout expired."},
            {13, "libcurl failed to get a sensible result back from the server as a response to either a PASV or a EPSV command."},
            {15, "An internal failure to lookup the host used for the new connection."},
            {17, "Received an error when trying to set the transfer mode to binary or ASCII."},
            {18, "A file transfer was shorter or larger than expected."},
            {19, "This was either a weird reply to a 'RETR' command or a zero byte transfer complete."},
            {21, "When sending custom \"QUOTE\" commands to the remote server, one of the commands returned an error code that was 400 or higher (for FTP) or otherwise indicated unsuccessful completion of the command."},
            {22, "This is returned if CURLOPT_FAILONERROR is set TRUE and the HTTP server returns an error code that is &gt;= 400."},
            {23, "An error occurred when writing received data to a local file, or an error was returned to libcurl from a write callback."},
            {25, "Failed starting the upload."},
            {26, "There was a problem reading a local file or an error returned by the read callback."},
            {27, "A memory allocation request failed."},
            {28, "Operation timeout."},
            {30, "The FTP PORT command returned error."},
            {31, "The FTP REST command returned error."},
            {33, "The server does not support or accept range requests."},
            {34, "This is an odd error that mainly occurs due to internal confusion."},
            {35, "A problem occurred somewhere in the SSL/TLS handshake."},
            {36, "The download could not be resumed because the specified offset was out of the file boundary."},
            {37, "A file given with FILE."},
            {38, "LDAP cannot bind."},
            {39, "LDAP search failed."},
            {41, "Function not found."},
            {42, "Aborted by callback."},
            {43, "A function was called with a bad parameter."},
            {45, "Interface error."},
            {47, "Too many redirects."},
            {48, "An option passed to libcurl is not recognized/known."},
            {49, "An option passed in to a setopt was wrongly formatted."},
            {52, "Nothing was returned from the server, and under the circumstances, getting nothing is considered an error."},
            {53, "The specified crypto engine was not found."},
            {54, "Failed setting the selected SSL crypto engine as default."},
            {55, "Failed sending network data."},
            {56, "Failure with receiving network data."},
            {58, "problem with the local client certificate."},
            {59, "Could not use specified cipher."},
            {60, "The remote server's SSL certificate or SSH fingerprint was deemed not OK."},
            {61, "Unrecognized transfer encoding."},
            {63, "Maximum file size exceeded."},
            {64, "Requested FTP SSL level failed."},
            {65, "When doing a send operation curl had to rewind the data to retransmit, but the rewinding operation failed."},
            {66, "Initiating the SSL Engine failed."},
            {67, "The remote server denied curl to login (Added in 7."},
            {68, "File not found on TFTP server."},
            {69, "Permission problem on TFTP server."},
            {70, "Out of disk space on the server."},
            {71, "Illegal TFTP operation."},
            {72, "Unknown TFTP transfer ID."},
            {73, "File already exists and is not overwritten."},
            {74, "This error should never be returned by a properly functioning TFTP server."},
            {77, "Problem with reading the SSL CA cert (path? access rights?)."},
            {78, "The resource referenced in the URL does not exist."},
            {79, "An unspecified error occurred during the SSH session."},
            {80, "Failed to shut down the SSL connection."},
            {81, "Socket is not ready for send/recv wait till it's ready and try again."},
            {82, "Failed to load CRL file (Added in 7."},
            {83, "Issuer check failed (Added in 7."},
            {84, "The FTP server does not understand the PRET command at all or does not support the given argument."},
            {85, "Mismatch of RTSP CSeq numbers."},
            {86, "Mismatch of RTSP Session Identifiers."},
            {87, "Unable to parse FTP file list (during FTP wildcard downloading)."},
            {88, "Chunk callback reported error."},
            {89, "(For internal use only, is never returned by libcurl) No connection available, the session is queued."},
            {90, "Failed to match the pinned key specified with CURLOPT_PINNEDPUBLICKEY."},
            {91, "Status returned failure when asked with CURLOPT_SSL_VERIFYSTATUS."},
            {93, "An API function was called from inside a callback."},
            {94, "An authentication function returned an error."},
            {96, "QUIC connection error."},
            {97, "Proxy handshake error."},
            {98, "SSL Client Certificate required."},
            {99, "An internal call to poll() or select() returned error that is not recoverable."},
            {100, "A value or data field grew larger than allowed."},
        };
    }
}
