# https://github.com/curl/curl/blob/68f96fc9bfce90c264d4d95b91135f3ef945eea8/include/curl/curl.h#L2850

curlinfo_definitions = """
CURLINFO_EFFECTIVE_URL    = CURLINFO_STRING + 1,
CURLINFO_RESPONSE_CODE    = CURLINFO_LONG   + 2,
CURLINFO_TOTAL_TIME       = CURLINFO_DOUBLE + 3,
CURLINFO_NAMELOOKUP_TIME  = CURLINFO_DOUBLE + 4,
CURLINFO_CONNECT_TIME     = CURLINFO_DOUBLE + 5,
CURLINFO_PRETRANSFER_TIME = CURLINFO_DOUBLE + 6,
CURLINFO_SIZE_UPLOAD_T    = CURLINFO_OFF_T  + 7,
CURLINFO_SIZE_DOWNLOAD_T  = CURLINFO_OFF_T  + 8,
CURLINFO_SPEED_DOWNLOAD_T = CURLINFO_OFF_T  + 9,
CURLINFO_HEADER_SIZE      = CURLINFO_LONG   + 11,
CURLINFO_REQUEST_SIZE     = CURLINFO_LONG   + 12,
CURLINFO_SSL_VERIFYRESULT = CURLINFO_LONG   + 13,
CURLINFO_FILETIME         = CURLINFO_LONG   + 14,
CURLINFO_FILETIME_T       = CURLINFO_OFF_T  + 14,
CURLINFO_CONTENT_LENGTH_DOWNLOAD_T = CURLINFO_OFF_T  + 15,
CURLINFO_CONTENT_LENGTH_UPLOAD_T   = CURLINFO_OFF_T  + 16,
CURLINFO_STARTTRANSFER_TIME = CURLINFO_DOUBLE + 17,
CURLINFO_CONTENT_TYPE     = CURLINFO_STRING + 18,
CURLINFO_REDIRECT_TIME    = CURLINFO_DOUBLE + 19,
CURLINFO_REDIRECT_COUNT   = CURLINFO_LONG   + 20,
CURLINFO_PRIVATE          = CURLINFO_STRING + 21,
CURLINFO_HTTP_CONNECTCODE = CURLINFO_LONG   + 22,
CURLINFO_HTTPAUTH_AVAIL   = CURLINFO_LONG   + 23,
CURLINFO_PROXYAUTH_AVAIL  = CURLINFO_LONG   + 24,
CURLINFO_OS_ERRNO         = CURLINFO_LONG   + 25,
CURLINFO_NUM_CONNECTS     = CURLINFO_LONG   + 26,
CURLINFO_SSL_ENGINES      = CURLINFO_SLIST  + 27,
CURLINFO_REDIRECT_URL     = CURLINFO_STRING + 31,
CURLINFO_PRIMARY_IP       = CURLINFO_STRING + 32,
CURLINFO_APPCONNECT_TIME  = CURLINFO_DOUBLE + 33,
CURLINFO_CERTINFO         = CURLINFO_PTR    + 34,
CURLINFO_CONDITION_UNMET  = CURLINFO_LONG   + 35,
CURLINFO_RTSP_SESSION_ID  = CURLINFO_STRING + 36,
CURLINFO_RTSP_CLIENT_CSEQ = CURLINFO_LONG   + 37,
CURLINFO_RTSP_SERVER_CSEQ = CURLINFO_LONG   + 38,
CURLINFO_RTSP_CSEQ_RECV   = CURLINFO_LONG   + 39,
CURLINFO_PRIMARY_PORT     = CURLINFO_LONG   + 40,
CURLINFO_LOCAL_IP         = CURLINFO_STRING + 41,
CURLINFO_TLS_SSL_PTR      = CURLINFO_PTR    + 45,
CURLINFO_HTTP_VERSION     = CURLINFO_LONG   + 46,
CURLINFO_TOTAL_TIME_T     = CURLINFO_OFF_T + 50,
CURLINFO_NAMELOOKUP_TIME_T = CURLINFO_OFF_T + 51,
CURLINFO_CONNECT_TIME_T   = CURLINFO_OFF_T + 52,
CURLINFO_PRETRANSFER_TIME_T = CURLINFO_OFF_T + 53,
CURLINFO_STARTTRANSFER_TIME_T = CURLINFO_OFF_T + 54,
CURLINFO_REDIRECT_TIME_T  = CURLINFO_OFF_T + 55,
CURLINFO_APPCONNECT_TIME_T = CURLINFO_OFF_T + 56,
CURLINFO_RETRY_AFTER      = CURLINFO_OFF_T + 57,
CURLINFO_EFFECTIVE_METHOD = CURLINFO_STRING + 58,
CURLINFO_PROXY_ERROR      = CURLINFO_LONG + 59,
CURLINFO_REFERER          = CURLINFO_STRING + 60,
CURLINFO_CAINFO           = CURLINFO_STRING + 61,
CURLINFO_CAPATH           = CURLINFO_STRING + 62,
CURLINFO_XFER_ID          = CURLINFO_OFF_T + 63,
CURLINFO_CONN_ID          = CURLINFO_OFF_T + 64,
CURLINFO_QUEUE_TIME_T     = CURLINFO_OFF_T + 65,
"""

# https://github.com/curl/curl/blob/68f96fc9bfce90c264d4d95b91135f3ef945eea8/include/curl/curl.h#L2840
base_values = {
    "CURLINFO_STRING": "0x100000",
    "CURLINFO_LONG": "0x200000",
    "CURLINFO_DOUBLE": "0x300000",
    "CURLINFO_SLIST": "0x400000",
    "CURLINFO_PTR": "0x400000",
    "CURLINFO_SOCKET": "0x500000",
    "CURLINFO_OFF_T": "0x600000"
}

csharp_enum = "public enum CurlInfo : int\n{\n"
for line in curlinfo_definitions.strip().split('\n'):
    parts = line.split('=')
    name = parts[0].strip()
    value = parts[1].strip().rstrip(',').split('+')
    base_type = value[0].strip()
    offset = value[1].strip()
    csharp_enum += f"    {name} = {base_values[base_type]} + {offset},\n"
csharp_enum += "}"

print(csharp_enum)